config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'patients#index'

get 'patients/list'
get 'patients/delete'

  resources :patients
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :patients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
before_action :authenticate_user!
layout 'standard'

    def index
        @search = Patient.search(params[:q])
        @patients = @search.result
    end

    def list
        @patients = Patient.all
    end

    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = current_user.patients.build
    end

    def create
        @patient = current_user.patients.build(patient_params)

        if @patient.save
            redirect_to :action => 'list'
        end
    end

    def patient_params
       params.require(:patients).permit(:name, :dateofbirth, :address, :phonenumber, :injury, :requestscan, :typeofscan)
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])

        if @patient.update_attributes(patient_param)
            redirect_to :action => 'show', :id => @patient
        else
            render :action => 'edit'
        end
    end

    def patient_param
        params.require(:patient).permit(:name, :dateofbirth, :address, :phonenumber, :injury, :requestscan, :typeofscan)
    end

    def delete
        Patient.find(params[:id]).destroy
        redirect_to :action => 'list'
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :authenticate_user!
layout 'standard'

    def index
    end

    def list
        @search = Patient.search(params[:q])
        @patients = @search.result
        if params[:q].blank?
            @patients = Patient.all
        end
    end

    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = current_user.patients.build
    end

    def create
        @patient = current_user.patients.build(patient_params)

        if @patient.save
            redirect_to :action => 'list'
        end
    end

    def patient_params
       params.require(:patients).permit(:name, :dateofbirth, :address, :phonenumber, :injury, :requestscan, :typeofscan, :appointmentdate, :appointmenttime)
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        @patient = Patient.find(params[:id])

        if @patient.update_attributes(patient_param)
            redirect_to :action => 'show', :id => @patient
        else
            render :action => 'edit'
        end
    end

    def patient_param
        params.require(:patient).permit(:name, :dateofbirth, :address, :phonenumber, :injury, :requestscan, :typeofscan, :appointmentdate, :appointmenttime)
    end

    def delete
        Patient.find(params[:id]).destroy
        redirect_to :action => 'list'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocApp</title>
    <%= csrf_meta_tags %>

     <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
     <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml">

   <head>
      <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
      <meta http-equiv = "Content-Language" content = "en-us" />
      <title>SHC-PMS</title>
      <%= stylesheet_link_tag "style" %>
   </head>

   <body id = "library">
      <div id="main-container" class="container-fluid">
        <div class="row">
         <div id = "header">
            <h1 class="bg-primary text-center">Smart Health Care - Patient Management System</h1>
         </div>

         <div id = "sidebar">


         <div id = "content">
         <ul class="nav navbar-nav">

               <li><%= link_to 'Homepage', {:action => 'index' }, :class => 'btn btn-primary navbar-btn' %></li>
               <li><%= link_to "Add new Patients", {:action => 'new' }, :class => 'btn btn-primary navbar-btn' %></li>
               <li><%= link_to "List all Patients", {:action => 'list' }, :class => 'btn btn-primary navbar-btn' %></li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
               <% if user_signed_in? %>
                 <li>
                    <%= link_to('Edit User Profile', edit_user_registration_path, :class => 'btn btn-primary navbar-btn') %>
                 </li>
                 <li>
                    <%= link_to('Logout', destroy_user_session_path, :class => 'btn btn-primary navbar-btn') %>
                 </li>
               <% else %>
                 <li>
                 <%= link_to('Login', new_user_session_path, :class => 'btn btn-primary navbar-btn')  %>
                 </li>
               <% end %>

             </ul>

            <%= yield -%>


         </div>


         </div>
        </div>
      </div>
   </body>

</html>

app/views/patient/list.html.erb
<% if @patients.blank? %>
<p>There are no patients in the system currently.</p>
<% else %>
<p>These are the current patients in the system</p>



<table class="table">
  <tr>
    <th>Name</th>
    <th >Date of Birth</th>
    <th >Address</th>
    <th >Phone Number</th>
    <th >Issue/Injury</th>
    <th >Scan Requested</th>
    <th >Type of Scan</th>
    <th >Doctor ID</th>
    <th >Doctor Contact Email</th>
    <th >Show</th>
    <th >Edit</th>
    <th >Delete</th>

  </tr>
  <% @patients.each do |patient| %>
  <tr>
    <td ><%= patient.name -%></td>
    <td ><%= patient.dateofbirth -%></td>
    <td ><%= patient.address -%></td>
    <td ><%= patient.phonenumber -%></td>
    <td ><%= patient.injury -%></td>
    <td ><%= patient.requestscan -%></td>
    <td><%= patient.typeofscan -%></td>
    <td><%= patient.user.id -%></td>
    <td><%= patient.user.email -%></td>
    <td><%= link_to 'Show', {:action => "show", :id => patient.id}, class: "btn btn-primary" %></td>
    <% if patient.user == current_user %>
        <td><%= link_to 'Edit', {:action => "edit", :id => patient.id}, class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', {:action => 'delete', :id => patient.id}, class: "btn btn-danger", confirm: "Are you sure you want to delete this record?" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<% end %>

app/views/patients/edit.html.erb
<br>
<br>
<h2 class="text-center">Edit patient details</h2>

<br>
<div class="container center_div">
<%= form_for @patient, :url =>{:action => "update", :id =>@patient} do |f| %>


<div class="form-group">
<label for = "patient_name" class="control-label col-sm-2">Name:</label>
<div class="col-sm-3">
<%= f.text_field 'name', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_dateofbirth" class="control-label col-sm-2">Date of Birth:</label>
<div class="col-sm-3">
<%= f.date_field  'dateofbirth', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_address" class="control-label col-sm-2">Address:</label>
<div class="col-sm-3">
<%= f.text_area  'address', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_phonenumber" class="control-label col-sm-2">Phone Number:</label>
<div class="col-sm-3">
<%= f.number_field  'phonenumber', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_injury" class="control-label col-sm-2">Injury:</label>
<div class="col-sm-3">
<%= f.text_area  'injury', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_requestscan" class="control-label col-sm-2">Request Scan:</label>
<div class="col-sm-3">
<%= f.text_field  'requestscan', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_typeofscan" class="control-label col-sm-2">Type of Scan:</label>
<div class="col-sm-3">
<%= f.text_field  'typeofscan', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_appointmentdate" class="control-label col-sm-2">Appointment Date:</label>
<div class="col-sm-3">
<%= f.date_select  'appointmentdate', :class => 'form-control' %>
</div>
</div>

<br>

<div class="form-group">
<label for = "patient_appointmenttime" class="control-label col-sm-2">Appointment Time:</label>
<div class="col-sm-3">
<%= f.time_select  'appointmenttime', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= f.submit "Save changes", :class => 'btn btn-primary' %>
</div>
</div>


<% end %>

<br>
<br>


<%= link_to 'Back', {:action => 'list' }, class: "btn btn-primary"%>

</div>

app/views/patients/index.html.erb
<br>
<br>
<br>

<h2 class="text-center">Welcome to the smart patient management system</h2>

<br>
<br>

<h4 class="text-center">The system allows you to add patients and assign appointment date and time to them. You can also view all patients and search for specific ones. </h4>

app/views/patients/list.html.erb
<br>
<br>

<h2 class="text-center">List and search patients</h2>

<br>


<div class="container center_div">
<%= search_form_for @search, url: patients_list_path do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.submit %>
<% end %>
</div>


<br>
<br>

<% if @patients.blank? %>
<p class="text-center">No patient records in the system!</p>
<% else %>
<p class="text-center">These are the current patients in the system</p>
<br>

<table class="table">
  <tr>
    <th> <%= sort_link @search, :name, "Name"%></th>
    <th> <%= sort_link @search, :dateofbirth, "Date of Birth"%></th>
    <th>Address</th>
    <th>Phone Number</th>
    <th> <%= sort_link @search, :injury, "Issue/Injury"%></th>
    <th> <%= sort_link @search, :requestscan, "Scan Requested"%></th>
    <th> <%= sort_link @search, :typeofscan, "Type of Scan"%></th>
    <th> <%= sort_link @search, :appointmentdate, "Appointment Date"%></th>
    <th >Appointment Time</th>
    <th >Doctor ID</th>
    <th >Doctor Contact Email</th>
    <th >Show</th>
    <th >Edit</th>
    <th >Delete</th>

  </tr>
  <% @patients.each do |patient| %>
  <tr>
    <td ><%= patient.name -%></td>
    <td ><%= patient.dateofbirth -%></td>
    <td ><%= patient.address -%></td>
    <td ><%= patient.phonenumber -%></td>
    <td ><%= patient.injury -%></td>
    <td ><%= patient.requestscan -%></td>
    <td><%= patient.typeofscan -%></td>
    <td><%= patient.appointmentdate -%></td>
    <td><%= patient.appointmenttime -%></td>
    <td><%= patient.user.id -%></td>
    <td><%= patient.user.email -%></td>
    <td><%= link_to 'Show', {:action => "show", :id => patient.id}, class: "btn btn-primary" %></td>
    <% if patient.user == current_user %>
        <td><%= link_to 'Edit', {:action => "edit", :id => patient.id}, class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', {:action => 'delete', :id => patient.id}, class: "btn btn-danger", confirm: "Are you sure you want to delete this record?" %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<% end %>

app/views/patients/new.html.erb
<br>
<br>
<h2 class="text-center">Add new patient</h2>

<br>
<div class="container center_div">
<%= form_tag :action => 'create', :class => 'form-horizontal' do %>

<div class="form-group">
<label for = "patient_name" class="control-label col-sm-2">Name:</label>
<div class="col-sm-3">
<%= text_field 'patients', 'name', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_dateofbirth" class="control-label col-sm-2">Date of Birth:</label>
<div class="col-sm-3">
<%= date_field 'patients', 'dateofbirth', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_address" class="control-label col-sm-2">Address:</label>
<div class="col-sm-3">
<%= text_area 'patients', 'address', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_phonenumber" class="control-label col-sm-2">Phone Number:</label>
<div class="col-sm-3">
<%= number_field 'patients', 'phonenumber', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_injury" class="control-label col-sm-2">Injury:</label>
<div class="col-sm-3">
<%= text_area 'patients', 'injury', :class => 'form-control' %>
</div>
</div>

<br>
<br>
<br>

<div class="form-group">
<label for = "patient_requestscan" class="control-label col-sm-2">Request Scan:</label>
<div class="col-sm-3">
<%= text_field 'patients', 'requestscan', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_typeofscan" class="control-label col-sm-2">Type of scan:</label>
<div class="col-sm-3">
<%= text_field 'patients', 'typeofscan', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_appointmentdate" class="control-label col-sm-2">Appointment Date:</label>
<div class="col-sm-3">
<%= date_select 'patients', 'appointmentdate', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<label for = "patient_appointmenttime" class="control-label col-sm-2">Appointment Time:</label>
<div class="col-sm-3">
<%= time_select 'patients', 'appointmenttime', :class => 'form-control' %>
</div>
</div>

<br>
<br>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<%= submit_tag "Create", :class => 'btn btn-primary'%>
</div>
</div>

<% end -%>
</div>

app/views/patients/search.html.erb
<ul id = "patients">
   <% @patients.each do |c| %>
   <li><%= link_to c.name, {:action => 'show', :id => c.id} -%><%= c.dateofbirth -%><%= c.address -%><%= c.phonenumber -%><%= c.injury -%><%= c.requestscan -%><%= c.typeofscan -%>
    <b> <%= link_to 'Edit', {:action => "edit", :id => c.id} %></b>
    <b> <%= link_to "Delete", {:action => 'delete', :id => c.id}, :confirm => "Are you sure you want to delete this record?" %></b>
   </li>
   <% end %>
</ul>

app/views/patients/show.html.erb
<br>
<br>
<h2 class="text-center">View patient details</h2>

<br>
<br>

<div class="container center_div">
<h3><%= @patient.name %></h3>

<p>
   <strong>Date of Birth: </strong> $<%= @patient.dateofbirth %><br />
   <strong>Address :</strong> <%= @patient.address %><br />
   <strong>Phone Number :</strong> <%= @patient.phonenumber %><br />
   <strong>Injury :</strong> <%= @patient.injury %><br />
   <strong>Request Scan :</strong> <%= @patient.requestscan %><br />
   <strong>Type of Scan :</strong> <%= @patient.typeofscan %><br />
   <strong>Appointment Date :</strong> <%= @patient.appointmentdate %><br />
   <strong>Appointment Time :</strong> <%= @patient.appointmenttime %><br />
   <strong>Doctor ID :</strong> <%= @patient.user.id %><br />
   <strong>Doctor Contact Email :</strong> <%= @patient.user.email %><br />
   <strong>Record creation date:</strong> <%= @patient.created_at %><br />
</p>

<hr/>
</div>

<%= link_to 'Back', {:action => 'list'}, class: "btn btn-primary" %>